# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
  # ...

  Gponty\IdLoomBundle\IdLoomApi:
    # redundant thanks to _defaults, but value is overridable on each service
    autowire: true
